kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: python:3.9.2-slim-buster
  environment:
    PASSWORD:
      from_secret: GH_TOKEN
  commands:
  - apt update -y
  - apt install sudo -y
  - sudo apt update -y
  - sudo apt install git -y
            
  - git clone https://dozzler555:$PASSWORD@github.com/dozzler555/vcom-alpha source
  - cd source
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt update -y
  - apt -qq update && apt -qq install -y git wget pv jq wget python3-dev ffmpeg mediainfo
  - apt -qq install -y git wget curl busybox  python3 ffmpeg python3-pip
  - pip3 install -r requirements.txt
  - sudo apt-get install -y python3-pip
  - bash start.sh
